//! `.d` file parser for GCC/Clang dependency files.
//!
//! Parses make-format dependency files generated by `-MD -MF` flags
//! to extract header dependencies for incremental compilation tracking.

use std::collections::HashSet;
use std::fs;
use std::path::Path;
use thiserror::Error;

/// Result type for `.d` file parsing
pub type Result<T> = std::result::Result<T, DFileError>;

/// Errors that can occur while parsing `.d` files
#[derive(Debug, Error)]
pub enum DFileError {
    #[error("failed to read .d file: {0}")]
    IoError(#[from] std::io::Error),
    #[error("invalid .d file format: {0}")]
    ParseError(String),
}

/// A parsed `.d` file containing header dependencies
#[derive(Debug, Clone)]
pub struct DFile {
    /// The source file this dependency file was generated for
    pub source_file: String,
    /// All header files this source depends on
    pub dependencies: Vec<String>,
    /// Target files (the actual object file, etc.)
    pub targets: Vec<String>,
}

impl DFile {
    /// Parse a `.d` file from text content
    pub fn parse(content: &str) -> Result<Self> {
        Self::parse_internal(content)
    }

    /// Parse a `.d` file from a path
    pub fn from_path(path: &Path) -> Result<Self> {
        let content = fs::read_to_string(path)?;
        let source_file = path
            .file_stem()
            .and_then(|s| s.to_str())
            .map(|s| s.replace(".d", ""))
            .unwrap_or_default();
        let mut dfile = Self::parse_internal(&content)?;
        dfile.source_file = source_file;
        Ok(dfile)
    }

    fn parse_internal(content: &str) -> Result<Self> {
        let mut dependencies = Vec::new();
        let mut targets = Vec::new();
        let source_file = "unknown".to_string();

        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }

            // Find the colon that separates targets from dependencies
            if let Some(colon_pos) = trimmed.find(':') {
                let target_part = &trimmed[..colon_pos];
                let dep_part = &trimmed[colon_pos + 1..];

                // Parse target(s)
                for target in Self::split_targets(target_part) {
                    let target_clean = Self::clean_path(target);
                    if !target_clean.is_empty() && !targets.contains(&target_clean) {
                        targets.push(target_clean);
                    }
                }

                // Parse dependencies
                for dep in Self::parse_dependency_line(dep_part) {
                    let dep_clean = Self::clean_path(&dep);
                    if !dep_clean.is_empty() && !dependencies.contains(&dep_clean) {
                        dependencies.push(dep_clean);
                    }
                }
            }
        }

        Ok(DFile {
            source_file,
            dependencies,
            targets,
        })
    }

    /// Get all unique header paths as a set
    pub fn header_set(&self) -> HashSet<String> {
        self.dependencies.iter().cloned().collect()
    }

    /// Filter to only include non-system headers
    pub fn user_headers(&self) -> Vec<&String> {
        self.dependencies
            .iter()
            .filter(|d| !is_system_header(d))
            .collect()
    }

    /// Filter to only include system headers
    pub fn system_headers(&self) -> Vec<&String> {
        self.dependencies
            .iter()
            .filter(|d| is_system_header(d))
            .collect()
    }

    fn split_targets(target_part: &str) -> Vec<&str> {
        target_part
            .split(|c| c == ' ' || c == '\t')
            .filter(|s| !s.is_empty())
            .collect()
    }

    fn clean_path(path: &str) -> String {
        // Remove escape characters and normalize
        let normalized = path.replace("\\ ", " ");
        normalized.trim().to_string()
    }

    fn parse_dependency_line(line: &str) -> Vec<String> {
        let mut deps = Vec::new();
        let mut current = String::new();
        let mut in_escape = false;

        for ch in line.chars() {
            if in_escape {
                match ch {
                    ' ' => current.push(' '),
                    'n' => current.push('\n'),
                    't' => current.push('\t'),
                    '\\' => current.push('\\'),
                    _ => {
                        current.push('\\');
                        current.push(ch);
                    }
                }
                in_escape = false;
            } else if ch == '\\' {
                in_escape = true;
            } else if ch == ' ' || ch == '\t' {
                if !current.is_empty() {
                    let cleaned = Self::clean_path(&current);
                    if !cleaned.is_empty() {
                        deps.push(cleaned);
                    }
                    current.clear();
                }
            } else {
                current.push(ch);
            }
        }

        if !current.is_empty() {
            let cleaned = Self::clean_path(&current);
            if !cleaned.is_empty() {
                deps.push(cleaned);
            }
        }

        deps
    }
}

/// Check if a header path is a system header
pub fn is_system_header(path: &str) -> bool {
    path.starts_with("/usr/")
        || path.starts_with("/include/")
        || path.starts_with("/usr/local/include")
        || path.starts_with("/opt/")
        || path.contains("/gcc/")
        || path.contains("/clang/")
}

/// Compute a hash of all dependencies for cache key generation
pub fn compute_dep_hash(deps: &[String]) -> String {
    use zigmera_hash::Blake3Hasher;
    let mut hasher = Blake3Hasher::with_schema_tag("c-dep-hash");
    let mut sorted = deps.to_vec();
    sorted.sort();
    for dep in sorted {
        hasher.update_str(&dep);
    }
    hasher.finalize().as_hex()[..16].to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_simple_d_file() {
        let content = "test.o: test.c stdio.h util.h\n";
        let dfile = DFile::parse(content).unwrap();
        assert_eq!(dfile.dependencies.len(), 3);
        assert!(dfile.dependencies.contains(&"test.c".to_string()));
        assert!(dfile.dependencies.contains(&"stdio.h".to_string()));
    }

    #[test]
    fn test_parse_multiline_d_file() {
        let content = "main.o: main.c header1.h header2.h\n";
        let dfile = DFile::parse(content).unwrap();
        assert!(dfile.dependencies.contains(&"main.c".to_string()));
        assert!(dfile.dependencies.contains(&"header1.h".to_string()));
        assert!(dfile.dependencies.contains(&"header2.h".to_string()));
    }

    #[test]
    fn test_parse_with_comments() {
        let content = "# Comment line\ntest.o: test.c header.h\n";
        let dfile = DFile::parse(content).unwrap();
        assert!(dfile.dependencies.contains(&"test.c".to_string()));
        assert!(dfile.dependencies.contains(&"header.h".to_string()));
    }

    #[test]
    fn test_system_header_detection() {
        assert!(is_system_header("/usr/include/stdio.h"));
        assert!(is_system_header("/usr/local/include/types.h"));
        assert!(!is_system_header("/home/user/project/header.h"));
        assert!(!is_system_header("./local_header.h"));
    }

    #[test]
    fn test_user_vs_system_headers() {
        let content = "test.o: test.c /usr/include/stdio.h ./local.h\n";
        let dfile = DFile::parse(content).unwrap();
        assert_eq!(dfile.user_headers().len(), 2); // test.c and local.h
        assert_eq!(dfile.system_headers().len(), 1); // stdio.h
    }

    #[test]
    fn test_compute_dep_hash() {
        let deps = vec!["a.h".to_string(), "b.h".to_string()];
        let hash1 = compute_dep_hash(&deps);
        // Order shouldn't matter
        let deps2 = vec!["b.h".to_string(), "a.h".to_string()];
        let hash2 = compute_dep_hash(&deps2);
        assert_eq!(hash1, hash2);
    }

    #[test]
    fn test_different_deps_different_hash() {
        let deps1 = vec!["a.h".to_string()];
        let hash1 = compute_dep_hash(&deps1);
        let deps2 = vec!["b.h".to_string()];
        let hash2 = compute_dep_hash(&deps2);
        assert_ne!(hash1, hash2);
    }
}